backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: about
    label: About
    folder: src/pages/about
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
      - {label: "Path", name: "path", widget: "hidden", default: "/about"}
      - {label: "Index", name: "index", widget: "number", valueType: "int", min: 1, default: 1}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Side Navigation Link Text", name: "navLinkText", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: ministries
    label: Ministries
    folder: src/pages/ministries
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "minitries"}
      - {label: "Index", name: "index", widget: "number", valueType: "int", min: 1, default: 1}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Side Navigation Link Text", name: "navLinkText", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Home
        name: home
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home"}
          - {label: "Path", name: "path", widget: "hidden", default: "/"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main", name: "main", widget: "object", fields: [{label: "Heading", name: "heading", widget: "string"}, {label: "Lead", name: "lead", widget: "string"}]}
          - {label: "Intro", name: "intro", widget: "object", fields: [{label: "Heading", name: "heading", widget: "string"}, {label: "Content", name: "content", widget: "text"}]}
          - {label: "Worship Service Info", name: "worshipServiceInfo", widget: "object", fields:[{label: "Heading", name: "heading", widget: "string"}, {label: "Time", name: "time", widget: "string"}, {label: "Location", name: "location", widget: "string"}, {label: "Room", name: "room", widget: "string"}, {label: "Street Address", name: "streetAddress", widget: "string"}, {label: "City", name: "city", widget: "string"}, {label: "State", name: "state", widget: "string"}, {label: "Zip Code", name: "zipCode", widget: "string"}]}
          - {label: "Key Verse", name: "keyVerse", widget: "object", fields: [{label: "Verse", name: "verse", widget: "text"}, {label: "Reference", name: "reference", widget: "string"}]}
      - file: src/pages/devotional/index.md
        label: Devotional
        name: devotional
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "devotional"}
          - {label: "Path", name: "path", widget: "hidden", default: "/devotional"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Daily Devotion Passages", name: "passagesUrl", widget: "file"}
      - file: src/pages/location/index.md
        label: Location
        name: location
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "location"}
          - {label: "Path", name: "path", widget: "hidden", default: "/location"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: src/pages/giving/index.md
        label: Giving
        name: giving
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "giving"}
          - {label: "Path", name: "path", widget: "hidden", default: "/giving"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}